version: "3"
services:
  hapi-fhir-jpaserver-start:
    image: hapi-fhir-jpaserver:tomcat
    container_name: hapi-fhir-jpaserver-start
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://hapi-fhir-postgres:5432/hapi"
      SPRING_DATASOURCE_USERNAME: "admin"
      SPRING_DATASOURCE_PASSWORD: "admin"
      SPRING_DATASOURCE_DRIVERCLASSNAME: "org.postgresql.Driver"
      JAVA_TOOL_OPTIONS: "-Xmx2g -Xms1g"
      HAPI_FHIR_AUTH_DISCOVERY_URL: "https://host.docker.internal:10000/.well-known/openid-configuration"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
    ports:
      - "8081:8080"
    depends_on:
      - hapi-fhir-postgres
  hapi-fhir-postgres:
    image: postgres:15-alpine
    container_name: hapi-fhir-postgres
    restart: always
    environment:
      POSTGRES_DB: "hapi"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    volumes:
      - hapi-fhir-postgres:/var/lib/postgresql/data
volumes:
  hapi-fhir-postgres: 